import { type ColorScheme } from "@/hooks/useTheme";
import { StyleSheet } from "react-native";

export const createStyles = (colors: ColorScheme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.bg,
      paddingHorizontal: 24,
    },
    header: {
      paddingVertical: 32,
      paddingBottom: 24,
    },
    titleContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 20,
    },
    iconContainer: {
      width: 56,
      height: 56,
      borderRadius: 16,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 16,
      backgroundColor: colors.primary,
    },
    titleTextContainer: {
      flex: 1,
    },
    title: {
      fontSize: 32,
      fontWeight: "700",
      letterSpacing: -1,
      marginBottom: 4,
      color: colors.text,
    },
    subtitle: {
      fontSize: 17,
      fontWeight: "500",
      color: colors.textMuted,
    },
    inputSection: {
      paddingBottom: 24,
    },
    inputWrapper: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      backgroundColor: colors.surface,
      borderRadius: 20,
      padding: 8,
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 8,
    },
    input: {
      flex: 1,
      fontSize: 17,
      paddingHorizontal: 16,
      paddingVertical: 12,
      color: colors.text,
      backgroundColor: colors.backgrounds.input,
      borderRadius: 16,
    },
    addButton: {
      width: 56,
      height: 56,
      borderRadius: 28,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: colors.primary,
      shadowColor: colors.primary,
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 8,
    },
    addButtonDisabled: {
      backgroundColor: colors.textMuted,
      opacity: 0.5,
      shadowOpacity: 0,
      elevation: 0,
    },
    todoItemWrapper: {
      marginVertical: 12,
    },
    todoItem: {
      flexDirection: "row" as const,
      alignItems: "flex-start" as const,
      padding: 20,
      borderRadius: 20,
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 8,
      backgroundColor: colors.surface,
    },
    checkbox: {
      marginRight: 16,
      marginTop: 2,
    },
    checkboxInner: {
      width: 32,
      height: 32,
      borderRadius: 16,
      borderWidth: 2,
      justifyContent: "center" as const,
      alignItems: "center" as const,
    },
    todoTextContainer: {
      flex: 1,
    },
    todoText: {
      fontSize: 17,
      lineHeight: 24,
      fontWeight: "500" as const,
      marginBottom: 16,
      color: colors.text,
    },
    todoActions: {
      flexDirection: "row" as const,
      gap: 12,
    },
    actionButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      justifyContent: "center" as const,
      alignItems: "center" as const,
      backgroundColor: colors.danger,
    },
    progressContainer: {
      marginTop: 8,
    },
    progressBarContainer: {
      flexDirection: "row" as const,
      alignItems: "center" as const,
      gap: 16,
    },
    progressBar: {
      flex: 1,
      height: 12,
      borderRadius: 6,
      overflow: "hidden" as const,
      backgroundColor: colors.border,
    },
    progressFill: {
      height: "100%" as const,
      borderRadius: 6,
      backgroundColor: colors.success,
    },
    progressText: {
      fontSize: 16,
      fontWeight: "700" as const,
      minWidth: 40,
      textAlign: "right" as const,
      color: colors.success,
    },
    editButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      justifyContent: "center" as const,
      alignItems: "center" as const,
      backgroundColor: colors.primary,
    },
    saveButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      justifyContent: "center" as const,
      alignItems: "center" as const,
      backgroundColor: colors.success,
    },
    cancelButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      justifyContent: "center" as const,
      alignItems: "center" as const,
      backgroundColor: colors.textMuted,
    },
    todoInput: {
      fontSize: 17,
      fontWeight: "500" as const,
      color: colors.text,
      backgroundColor: colors.backgrounds.editInput,
      borderColor: colors.border,
      borderWidth: 1,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 6,
      marginBottom: 16,
    },
    logoutButton: {
      padding: 12,
      borderRadius: 20,
      backgroundColor: colors.dangerLight,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    logoutText: {
      fontSize: 16,
      fontWeight: "600",
    },
  });
